TAXONOMY_STR = """
================================================================================
MARKET SEGMENT: AIR PLATFORMS
Definition: Any vehicle or system capable of atmospheric flight used for military operations, including piloted aircraft and unmanned aerial vehicles (UAVs).
Example: "The air force is looking to acquire new jets and helicopters for the upcoming fiscal year."

--- System Type (General): Fixed Wing
    Definition: Aircraft where lift is generated by forward motion and non-rotating wings.
    Example: "The fleet includes F-35 jets and C-130 transport planes."
    
    System Type (Specific):
    1. Fighter: Fast, maneuverable aircraft designed for air-to-air combat and air superiority. (Example: F-16 Fighting Falcon, Su-35, Rafale)
    2. Bomber: Large aircraft designed to carry heavy payloads of air-to-ground ordnance for strategic strikes. (Example: B-52 Stratofortress, B-2 Spirit, H-6)
    3. Light Combat Aircraft: Smaller, lower-cost fighters used for light attack or advanced training. (Example: Tejas LCA, FA-50, Yak-130)
    4. Gunship: Transport airframes modified with heavy side-firing guns for close air support. (Example: AC-130J Ghostrider)
    5. Trainers: Aircraft dedicated to teaching pilots flight skills. (Example: T-7 Red Hawk, Pilatus PC-21)
    6. Tanker: Aircraft equipped to refuel other planes in mid-air. (Example: KC-46 Pegasus, A330 MRTT)
    7. Maritime Aircraft: Fixed-wing planes for anti-submarine or anti-surface warfare over the ocean. (Example: P-8 Poseidon, CN-235 MPA)
    8. ISR-Strike: Drones (UAVs) capable of both surveillance and firing missiles. (Example: MQ-9 Reaper, Bayraktar TB2)
    9. C4ISR: Manned aircraft dedicated to signals intelligence or surveillance without large command radars. (Example: RC-135 Rivet Joint, King Air ISR)
    10. AEW&C: Aircraft with a large radar (rotodome/bar) for air battle management. (Example: E-3 Sentry AWACS, E-2 Hawkeye)
    11. Transport Aircraft: Planes for moving troops, cargo, and vehicles. (Example: C-17 Globemaster, A400M)
    12. Target Drone: Unmanned aircraft used as practice targets for weapons training. (Example: BQM-167 Aerial Target)
    13. Fixed Wing Other: Miscellaneous fixed-wing aircraft like gliders or VIP transport. (Example: Presidential transport jet)
    14. Not Applicable: General reference to fixed-wing aircraft without specific type.

--- System Type (General): Rotary Wing
    Definition: Aircraft that generate lift via spinning rotor blades (helicopters).
    Example: "The army deployed attack helicopters to the region."

    System Type (Specific):
    1. Rotary Wing Attack: Heavily armed helicopters for anti-tank and ground support roles. (Example: AH-64 Apache, Eurocopter Tiger)
    2. Rotary Wing Maritime: Helicopters operating from ships for ASW/ASuW. (Example: MH-60R Seahawk, NH90 NFH)
    3. Rotary Wing Scout: Light helicopters for reconnaissance and observation. (Example: OH-58 Kiowa, Kawasaki OH-1)
    4. Rotary Wing Transport: Helicopters for moving troops or cargo. (Example: CH-47 Chinook, UH-60 Black Hawk, Mi-17)
    5. Rotary Wing Other: Search and Rescue (SAR) or Medevac helicopters. (Example: HH-60 Pave Hawk)
    6. C4ISR: Unmanned rotary-wing drones for surveillance. (Example: MQ-8 Fire Scout)
    7. ISR-Strike: Unmanned rotary-wing drones with weapons. (Example: Armed VTOL UAV)
    8. Not Applicable: General reference to helicopters without specific type.

--- System Type (General): Other Lift Types
    Definition: Aerial platforms using alternative lift methods (buoyancy, tilt-rotors, parafoils).
    Example: "The marines use tilt-rotors for rapid deployment."

    System Type (Specific):
    1. Hybrid: Aircraft combining vertical takeoff with fixed-wing flight. (Example: V-22 Osprey Tilt-rotor)
    2. Airship: Lighter-than-air powered blimps. (Example: High-altitude surveillance aerostat)
    3. Parafoil: Powered parachutes. (Example: CQ-10 Snowgoose)
    4. Not Applicable: Other non-standard lift types.

--- System Type (General): Not Applicable
    Definition: Reference to Air Platforms generally without specifying a system.
    Example: "The aviation budget has increased."

================================================================================
MARKET SEGMENT: LAND PLATFORMS
Definition: Military vehicles and equipment designed for ground operations, including armor, artillery, and logistics.
Example: "The army is modernizing its vehicle fleet with new tanks and trucks."

--- System Type (General): Artillery
    Definition: Large-caliber weapons for firing projectiles over long distances (indirect fire).
    Example: "The battalion fired 155mm howitzers at the enemy position."

    System Type (Specific):
    1. Self-Propelled Artillery: A howitzer mounted on a vehicle chassis that drives itself. (Example: M109 Paladin, K9 Thunder)
    2. Towed Artillery: A gun pulled by a truck. (Example: M777 Howitzer)
    3. Mortar: A tube weapon firing high-angle projectiles. (Example: 81mm Mortar, M120)
    4. Other: Coastal defense guns or railway guns.
    5. Not Applicable: General reference to artillery.

--- System Type (General): Armoured Fighting Vehicles
    Definition: Combat vehicles protected by armor, ranging from tanks to troop carriers.
    Example: "The mechanized infantry moved forward in their armored carriers."

    System Type (Specific):
    1. Main Battle Tank: The primary heavy tank with a large gun and heavy armor. (Example: M1 Abrams, Leopard 2, T-90)
    2. Armoured All-Terrain Vehicle: Tracked, articulated vehicles for snow/swamp. (Example: BvS10 Viking)
    3. Armoured Utility/Protected Patrol Vehicles: Wheeled vehicles with mine protection (MRAP). (Example: JLTV, Cougar MRAP, Humvee)
    4. Tracked Armoured Fighting Vehicles: Infantry Fighting Vehicles (IFV) on tracks. (Example: M2 Bradley, CV90)
    5. Wheeled Armoured Fighting Vehicles: IFVs or APCs on 6x6 or 8x8 wheels. (Example: Stryker, Boxer 8x8)
    6. Amphibious Assault Vehicles: Armored vehicles that swim from ship to shore. (Example: AAV-7, ACV)
    7. Light Tank: Smaller tanks for air-deployment. (Example: M10 Booker)
    8. Other: Prototype armored vehicles.
    9. Not Applicable: General reference to armored vehicles.

--- System Type (General): Logistics & Support
    Definition: Vehicles and equipment for transport, engineering, medical, and supply roles.
    Example: "The convoy of trucks delivered supplies to the base."

    System Type (Specific):
    1. All-Terrain Vehicles: Small quad bikes or buggies. (Example: Polaris MRZR)
    2. Combat Engineering Vehicles: Armored dozers or breachers. (Example: M9 ACE, Trojan AVRE)
    3. Construction Vehicles: Standard excavators and cranes. (Example: Military bulldozer)
    4. Engineering Equipment: Generators and power tools.
    5. Light Tactical/Utility Vehicles: Soft-skinned jeeps or pickup trucks. (Example: Land Rover Defender, Toyota Hilux Technical)
    6. Medical Equipment: Field ambulances. (Example: Humvee Ambulance)
    7. Military Bridges: Bridgelaying vehicles. (Example: M60 AVLB)
    8. NBC Equipment: Hazmat detection vehicles. (Example: Fuchs CBRN)
    9. Trucks: Heavy cargo trucks. (Example: HEMTT, MAN HX Series)
    10. Other: Kitchen trucks, water purification.
    11. Not Applicable: General reference to logistics vehicles.

--- System Type (General): Rolling Stock
    Definition: Military railway assets.
    Example: "Tanks were loaded onto the train for transport."

    System Type (Specific):
    1. Not Applicable: (Only one option) Trains and railway wagons.

--- System Type (General): Other Land
    Definition: Specialized land systems not fitting the vehicle categories.
    Example: "Soldiers were equipped with new exoskeletons."

    System Type (Specific):
    1. Soldier Fighting Systems: Wearable tech and body armor. (Example: Integrated Visual Augmentation System)
    2. Other: Unmanned Ground Vehicles (UGVs). (Example: Themis UGV)
    3. Not Applicable: General other.

--- System Type (General): Not Applicable
    Definition: Reference to Land Platforms generally.

================================================================================
MARKET SEGMENT: NAVAL PLATFORMS
Definition: Surface ships and submarines used for maritime warfare and support.
Example: "The navy is commissioning a new class of destroyers."

--- System Type (General): Sub-Surface
    Definition: Vessels operating underwater.
    Example: "The submarine conducted a stealth patrol."

    System Type (Specific):
    1. Diesel-Powered Submarine: Conventional sub using batteries/diesel. (Example: Type 212, Kilo Class)
    2. Nuclear-Powered Submarine: Sub with a nuclear reactor. (Example: Virginia Class, Astute Class)
    3. Other: Midget subs or rescue submersibles.
    4. Not Applicable: General reference to submarines.

--- System Type (General): Surface Combatants
    Definition: Major warships for open-ocean warfare.
    Example: "The carrier strike group includes cruisers and frigates."

    System Type (Specific):
    1. Aircraft Carrier: Ship with a flight deck for jets. (Example: USS Gerald R. Ford, HMS Queen Elizabeth)
    2. Cruisers: Large, heavily armed warships. (Example: Ticonderoga Class)
    3. Destroyers: Multi-mission escorts. (Example: Arleigh Burke Class, Type 45)
    4. Frigates: Medium escorts, often ASW focused. (Example: FREMM, Type 26)
    5. Corvettes: Small coastal warships. (Example: Visby Class)
    6. Other Surface Combatants: Littoral Combat Ships (LCS).
    7. Not Applicable: General reference to warships.

--- System Type (General): Patrol and Coastal Combatants
    Definition: Smaller vessels for border protection and constabulary duties.
    Example: "The coast guard intercepted the vessel with a patrol boat."

    System Type (Specific):
    1. Patrol Boat/Craft - Coastal: Small interceptors. (Example: Mark VI Patrol Boat)
    2. Patrol Boat/Craft - Ocean: Offshore Patrol Vessels (OPV). (Example: River Class OPV)
    3. Patrol Boat/Craft - Riverine: Shallow water boats. (Example: SOC-R)
    4. Other: Unmanned patrol boats.
    5. Not Applicable: General patrol craft.

--- System Type (General): Mine Warfare/MCM
    Definition: Ships for laying or clearing sea mines.
    Example: "The harbor was cleared by a minesweeper."

    System Type (Specific):
    1. Mine Sweeper: Cuts mine cables. (Example: Avenger Class)
    2. Mine Counter-Measures: General MCM vessels.
    3. Mine Hunter: Finds mines via sonar. (Example: Sandown Class)
    4. Other: Drone mine hunters.
    5. Not Applicable: General mine warfare ships.

--- System Type (General): Amphibious
    Definition: Ships for landing troops on a beach.
    Example: "Marines boarded the landing craft to storm the shore."

    System Type (Specific):
    1. Amphibious Assault Ship: Small carrier with internal dock. (Example: Wasp Class LHD)
    2. Landing Ship: Beaches to unload. (Example: Ropucha Class)
    3. Landing Craft: Small boat for ship-to-shore. (Example: LCU)
    4. Landing Platform Dock: Transport with well deck. (Example: San Antonio Class)
    5. Other: Expeditionary fast transport.
    6. Not Applicable: General amphibious ships.

--- System Type (General): Logistics & Support (Maritime)
    Definition: Non-combatant auxiliary ships.
    Example: "The fleet was refueled by an oiler."

    System Type (Specific):
    1. Research/Survey Vessels: Ocean mapping ships.
    2. Icebreakers: Ships for polar regions.
    3. Combat Support Ship: Fast supply ships. (Example: Supply Class)
    4. Repair Ships: Floating workshops.
    5. Tanker/Cargo/Oiler: Fuel and cargo ships. (Example: John Lewis Class Oiler)
    6. Hospital Ship: Medical treatment vessel. (Example: USNS Mercy)
    7. Logistics and Support Other (Maritime): Tugs, salvage ships.
    8. Not Applicable: General support ships.

--- System Type (General): Other Maritime
    Definition: Miscellaneous naval assets.
    Example: "Cadets trained on the sailing ship."

    System Type (Specific):
    1. Training Ship: Dedicated training vessel.
    2. Other Maritime: Unmanned Surface Vehicles (USV).
    3. Not Applicable: General other.

--- System Type (General): Not Applicable
    Definition: Reference to Naval Platforms generally.

================================================================================
MARKET SEGMENT: SPACE SYSTEMS
Definition: Assets operating outside Earth's atmosphere.
Example: "The satellite was launched into orbit."

--- System Type (General): Launch Vehicle
    Definition: Rockets for reaching space.
    Example: "The payload was carried by a heavy lift rocket."

    System Type (Specific):
    1. Launch Vehicle: The rocket itself. (Example: Falcon 9, Atlas V)
    2. Not Applicable: General launch reference.

--- System Type (General): Satellite
    Definition: Orbital payloads.
    Example: "The military communications satellite is now operational."

    System Type (Specific):
    1. Satellite: Comms or GPS satellite. (Example: GPS III, WGS)
    2. Radar Satellite: SAR imaging satellite. (Example: Lacrosse)
    3. Other: Early warning satellite.
    4. Not Applicable: General satellite reference.

--- System Type (General): Anti-Space
    Definition: Weapons targeting space assets.
    Example: "They tested an anti-satellite missile."

    System Type (Specific):
    1. Anti-Space: ASAT missiles or jammers. (Example: Nudol)
    2. Not Applicable: General anti-space.

--- System Type (General): Other
    Definition: Space stations or planes.
    System Type (Specific):
    1. Other: Spaceplane. (Example: X-37B)

--- System Type (General): Not Applicable
    Definition: Reference to Space Systems generally.

================================================================================
MARKET SEGMENT: C4ISR SYSTEMS
Definition: Command, Control, Communications, Computers, Intelligence, Surveillance, and Reconnaissance systems.
Example: "The new radar and radio systems will improve situational awareness."

--- System Type (General): Electro-optic Sensor
    Definition: Cameras and thermal imagers.
    Example: "The drone uses an infrared camera."

    System Type (Specific):
    1. Imaging EO/IR: Surveillance cameras. (Example: FLIR Star Safire)
    2. Targeting EO/IR: Laser designator pods. (Example: Sniper ATP)
    3. Other: Laser rangefinders.
    4. Not Applicable: General sensors.

--- System Type (General): Radar
    Definition: Radio detection and ranging systems.
    Example: "The air defense radar tracked the incoming plane."

    System Type (Specific):
    1. Air Search Radar: Long range sky scan. (Example: TPS-77)
    2. Surface Surveillance Radar: Sea/Ground scan. (Example: Giraffe AMB)
    3. Fire Control Radar: Target lock-on. (Example: AN/SPG-62)
    4. Navigation Radar: Ship/Plane safety radar.
    5. Weather Radar: Meteorological radar.
    6. Multi-Mission Radar: AESA radars doing multiple tasks. (Example: AN/SPY-6)
    7. Other: Ground penetrating radar.
    8. Not Applicable: General radar.

--- System Type (General): Sonar
    Definition: Acoustic detection systems.
    Example: "The frigate used sonar to find the submarine."

    System Type (Specific):
    1. Sonar: Active or passive sonar. (Example: Towed array sonar)
    2. Not Applicable: General sonar.

--- System Type (General): Command and Control
    Definition: Systems for managing battles.
    Example: "The HQ uses battle management software."

    System Type (Specific):
    1. Command and Control System: BMS software. (Example: SitaWare)
    2. Not Applicable: General C2.

--- System Type (General): Communications
    Definition: Voice and data transmission.
    Example: "Secure radios were distributed to the squad."

    System Type (Specific):
    1. Radios: Handheld or vehicle radios. (Example: Harris Falcon III)
    2. Data Links: Tactical networks. (Example: Link 16)
    3. Satellite Communications: Satcom terminals. (Example: VSAT)
    4. Other: Intercoms.
    5. Not Applicable: General comms.

--- System Type (General): Cyber
    Definition: Digital network operations.
    Example: "The firewall prevented a cyber attack."

    System Type (Specific):
    1. Cyber Defense: Protection software.
    2. Cyber Offense: Hacking tools.
    3. Military IT Systems: Admin networks.
    4. Other: Cyber ranges.
    5. Not Applicable: General cyber.

--- System Type (General): Defensive Systems
    Definition: Self-protection suites.
    Example: "The tank used its active protection system to stop the missile."

    System Type (Specific):
    1. Defensive Aid Suite: APS or DASS. (Example: Trophy APS)
    2. Not Applicable: General defensive aids.

--- System Type (General): Integrated C4ISR System
    Definition: Large multi-domain networks.
    System Type (Specific):
    1. Integrated C4ISR System: Border security network.
    2. Not Applicable: General integrated systems.

--- System Type (General): Artificial Intelligence
    Definition: AI algorithms.
    System Type (Specific):
    1. Artificial Intelligence: Machine learning models.
    2. Not Applicable: General AI.

--- System Type (General): Other C4ISR
    Definition: Positioning and other electronics.
    System Type (Specific):
    1. PNT Systems: GPS devices. (Example: DAGR)
    2. Other: Unclassified electronics.
    3. Not Applicable: General other.

--- System Type (General): Not Applicable
    Definition: Reference to C4ISR generally.

================================================================================
MARKET SEGMENT: WEAPON SYSTEMS
Definition: Devices designed to inflict damage or neutralize targets.
Example: "The contract includes missiles, bombs, and small arms."

--- System Type (General): Missile
    Definition: Self-propelled guided projectiles.
    Example: "The jet fired an air-to-air missile."

    System Type (Specific):
    1. Air-to-Air: Jet vs Jet. (Example: AIM-9X Sidewinder)
    2. Air-to-Surface: Jet vs Ground. (Example: AGM-65 Maverick)
    3. Air-to-Ship: Jet vs Ship. (Example: AGM-84 Harpoon)
    4. Surface-to-Air: Ground vs Jet. (Example: Patriot PAC-3)
    5. Surface-to-Surface: Ground vs Ground. (Example: ATACMS)
    6. Surface-to-Ship: Coast vs Ship. (Example: NSM Coastal Battery)
    7. Ship-to-Air: Ship vs Jet. (Example: SM-2)
    8. Ship-to-Surface: Ship vs Ground. (Example: Tomahawk)
    9. Ship-to-Ship: Ship vs Ship. (Example: RBS-15)
    10. Ballistic Missile: Space trajectory. (Example: Minuteman III)
    11. Other: Hypersonic glide vehicle.
    12. Not Applicable: General missile.

--- System Type (General): Precision Guided Weapons
    Definition: Guided munitions that are dropped or fired (not self-propelled missiles).
    Example: "Smart bombs were used for the strike."

    System Type (Specific):
    1. Guided Rocket: Guided 70mm rockets. (Example: APKWS)
    2. Guided Bomb: Smart gravity bombs. (Example: JDAM, Paveway)
    3. Guided Artillery Round: Smart shells. (Example: Excalibur)
    4. Loitering Munitions: Suicide drones. (Example: Switchblade 600)
    5. Other: Glide bombs.
    6. Not Applicable: General PGW.

--- System Type (General): Torpedo
    Definition: Underwater self-propelled weapons.
    Example: "The sub fired a heavy torpedo."

    System Type (Specific):
    1. Heavy Weight Torpedo: Submarine launched. (Example: Mk48 ADCAP)
    2. Light Weight Torpedo: Air/Ship launched. (Example: Mk54)
    3. Other: Supercavitating torpedo.
    4. Not Applicable: General torpedo.

--- System Type (General): Directed Energy Weapon
    Definition: Lasers or microwaves.
    Example: "The laser burned through the drone."

    System Type (Specific):
    1. Radar: RF weapon.
    2. Laser: High energy laser. (Example: HELIOS)
    3. Microwave: Electronic frier. (Example: THOR)
    4. Sonic: Acoustic weapon. (Example: LRAD)
    5. Other: Particle beam.
    6. Not Applicable: General DEW.

--- System Type (General): Integrated Weapon Systems
    Definition: Multi-component weapon complexes.
    Example: "The air defense battery was deployed."

    System Type (Specific):
    1. Air and Missile Defense System: Area defense. (Example: Iron Dome)
    2. Ballistic Missile Defense System: Anti-ICBM. (Example: THAAD)
    3. Coastal Defense System: Anti-ship batteries.
    4. Border Defense System: Sentry towers.
    5. Remote Weapon System: Turret on vehicle. (Example: CROWS)
    6. Counter-UAS System: Anti-drone. (Example: Drone Dome)
    7. Naval Gun: Ship cannon. (Example: Mk45 5-inch gun)
    8. Other: Modular turrets.
    9. Not Applicable: General integrated.

--- System Type (General): Electronic Warfare Systems
    Definition: Jammers and electronic attack.
    Example: "The pod jammed the enemy radar."

    System Type (Specific):
    1. Electronic Jamming: Noise jamming. (Example: AN/ALQ-99)
    2. Electronic Attack: Targeted disruption.
    3. Other: ESM.
    4. Not Applicable: General EW.

--- System Type (General): Small Arms & Ammunition
    Definition: Guns and bullets.
    Example: "Troops were issued new rifles and ammo."

    System Type (Specific):
    1. Small Arms: Rifles/pistols. (Example: M4 Carbine)
    2. Ammunition: Bullets. (Example: 5.56mm NATO)
    3. Rockets: Unguided RPGs. (Example: RPG-7)
    4. Bombs: Dumb bombs. (Example: Mk82)
    5. Explosives: C4/TNT.
    6. Decoy Flares: Countermeasures. (Example: MJU-7 Flare)
    7. Other: Grenades.
    8. Not Applicable: General small arms.

--- System Type (General): Mines
    Definition: Static explosive traps.
    Example: "The field was cleared of landmines."

    System Type (Specific):
    1. Anti-Personnel Mine: Anti-infantry.
    2. Anti-Tank Mine: Anti-vehicle.
    3. Sea Mine: Underwater mine.
    4. Mine Dispersal System: Scattering system. (Example: Volcano)
    5. Not Applicable: General mines.

--- System Type (General): Launchers
    Definition: Firing mechanisms.
    Example: "The missile launcher was damaged."

    System Type (Specific):
    1. Launchers: Rails/Tubes. (Example: M299 Launcher)
    2. Other: Pneumatic.
    3. Not Applicable: General launcher.

--- System Type (General): Swarm Drones
    Definition: Coordinated drone attacks.
    System Type (Specific):
    1. EW Swarm Drones: Jamming swarm.
    2. Kinetic Strike Swarm Drones: Attack swarm.
    3. Other: Recon swarm.
    4. Not Applicable: General swarm.

--- System Type (General): Not Applicable
    Definition: Reference to Weapon Systems generally.

================================================================================
MARKET SEGMENT: INFRASTRUCTURE
Definition: Physical facilities supporting military operations.
Example: "Construction of the new airbase is complete."

--- System Type (General): Shipyards/Ports/Harbours
    Definition: Naval docking and construction facilities.
    System Type (Specific):
    1. Not Applicable: Docks, piers, drydocks, naval bases.

--- System Type (General): Aircraft Basing
    Definition: Aviation facilities.
    System Type (Specific):
    1. Not Applicable: Hangars, runways, airfields, control towers (structural).

--- System Type (General): Accommodation
    Definition: Housing for personnel.
    System Type (Specific):
    1. Not Applicable: Barracks, dormitories, mess halls, family housing.

--- System Type (General): Non-military IT
    Definition: General office computing infrastructure.
    System Type (Specific):
    1. Not Applicable: Office computers, payroll software, enterprise servers.

--- System Type (General): Land
    Definition: Real estate and physical territory.
    System Type (Specific):
    1. Not Applicable: Training grounds, maneuver areas, land acquisition.

--- System Type (General): Training Facilities
    Definition: Physical buildings for instruction (not simulators).
    System Type (Specific):
    1. Not Applicable: Classrooms, shooting ranges, obstacle courses.

--- System Type (General): Air Traffic Management
    Definition: Infrastructure for managing airspace.
    System Type (Specific):
    1. Not Applicable: Control towers, radar stations (civil/military mix).

--- System Type (General): Maintenance Facilities
    Definition: Workshops for repair.
    System Type (Specific):
    1. Not Applicable: Repair depots, workshops, maintenance bays.

--- System Type (General): Production Facilities
    Definition: Manufacturing plants.
    System Type (Specific):
    1. Not Applicable: Factories, assembly lines, ammunition plants.

--- System Type (General): RDT&E Facilities
    Definition: Research and test centers.
    System Type (Specific):
    1. Not Applicable: Laboratories, wind tunnels, test ranges, proving grounds.

--- System Type (General): Utilities
    Definition: Base support services.
    System Type (Specific):
    1. Not Applicable: Power generation, water treatment, sewage, heating.

--- System Type (General): Other
    Definition: Miscellaneous infrastructure.
    System Type (Specific):
    1. Not Applicable: Fencing, security gates, roads on base.

--- System Type (General): Not Applicable
    Definition: Reference to Infrastructure generally.

================================================================================
MARKET SEGMENT: TRAINING & SIMULATION
Definition: Systems for virtual or synthetic training.
Example: "Pilots are training on the new flight simulator."

--- System Type (General): Simulators
    Definition: Hardware/Software imitating real systems.
    System Type (Specific):
    1. Not Applicable: Flight simulators, driving simulators, VR headsets.

--- System Type (General): Training Aids
    Definition: Physical classroom tools.
    System Type (Specific):
    1. Not Applicable: Mock-ups, charts, dummy weapons, instructional models.

--- System Type (General): Other
    Definition: Services or non-hardware training.
    System Type (Specific):
    1. Not Applicable: Live training services, role players, instructors.

--- System Type (General): Not Applicable
    Definition: Reference to Training generally.

================================================================================
MARKET SEGMENT: UNKNOWN
Definition: Text that cannot be categorized into the defense taxonomy.
Example: "The weather report for tomorrow is sunny."

--- System Type (General): Not Applicable
    Definition: Irrelevant data.
    System Type (Specific):
    1. Not Applicable: Irrelevant or ambiguous text, administrative data, noise.
"""

VALID_DEPENDENCIES = {
    "C4ISR Systems": [
        "Electro-optic Sensor", "Radar", "Sonar", "Command and Control",
        "Communications", "Cyber", "Defensive Systems", "Integrated C4ISR System",
        "Artificial Intelligence", "Other C4ISR", "Not Applicable"
    ],
    "Air Platforms": ["Fixed-Wing", "Rotary Wing", "Other Lift Types", "Not Applicable"],
    "Land Platforms": [
        "Artillery", "Armoured Fighting Vehicles", "Logistics & Support",
        "Rolling Stock", "Other Land", "Not Applicable"
    ],
    "Naval Platforms": [
        "Sub-Surface", "Surface Combatants", "Patrol and Coastal Combatants",
        "Mine Warfare/MCM", "Amphibious", "Logistics & Support (Maritime)",
        "Other Maritime", "Not Applicable"
    ],
    "Space Systems": ["Launch Vehicle", "Satellite", "Anti-Space", "Other", "Not Applicable"],
    "Weapon Systems": [
        "Missile", "Precision Guided Weapons", "Torpedo", "Directed Energy Weapon",
        "Integrated Weapon Systems", "Electronic Warfare Systems",
        "Small Arms & Ammunition", "Mines", "Launchers", "Swarm Drones", "Not Applicable"
    ],
    "Infrastructure": ["Not Applicable"],
    "Training & Simulation": ["Simulators", "Training Aids", "Other", "Not Applicable"],
    "Unknown": ["Not Applicable"]
}

# (Keep GEOGRAPHY_MAPPING, VALID_OPERATORS, SUPPLIER_LIST, PROGRAM_TYPES, DOMESTIC_CONTENT_OPTIONS as they were in your original code)
GEOGRAPHY_MAPPING = {
    "Sub-Saharan Africa": [
        "Angola", "Benin", "Botswana", "Burkina Faso", "Burundi", "Cameroon", "Cape Verde",
        "Central African Republic", "Chad", "Congo, Democratic Republic of", "Congo, Republic of",
        "Djibouti", "Equatorial Guinea", "Eritrea", "Eswatini", "Ethiopia", "Gabon", "Gambia",
        "Ghana", "Guinea", "Guinea-Bissau", "Ivory Coast", "Kenya", "Lesotho", "Liberia",
        "Madagascar", "Malawi", "Mali", "Mauritius", "Mozambique", "Namibia", "Niger",
        "Nigeria", "Rwanda", "Senegal", "Seychelles", "Sierra Leone", "Somalia", "South Africa",
        "South Sudan", "Sudan", "Tanzania", "Togo", "Uganda", "Zambia", "Zimbabwe"
    ],
    "Asia-Pacific": [
        "Australia", "Brunei", "Cambodia", "China", "Hong Kong", "Indonesia", "Japan", "Laos",
        "Malaysia", "Mongolia", "Myanmar", "New Zealand", "North Korea", "Papua New Guinea",
        "Philippines", "Singapore", "South Korea", "Taiwan", "Thailand", "Vietnam"
    ],
    "Europe": [
        "Albania", "Austria", "Belgium", "Bosnia and Herzegovina", "Bulgaria", "Croatia", "Cyprus",
        "Czech Republic", "Denmark", "Estonia", "Finland", "France", "Georgia", "Germany", "Greece",
        "Hungary", "Iceland", "Ireland", "Italy", "Kosovo", "Latvia", "Lithuania", "Luxembourg",
        "Malta", "Montenegro", "Netherlands", "North Macedonia", "Norway", "Poland", "Portugal",
        "Romania", "Serbia", "Slovakia", "Slovenia", "Spain", "Sweden", "Switzerland", "Turkey",
        "Ukraine", "United Kingdom"
    ],
    "Latin America": [
        "Argentina", "Bahamas", "Barbados", "Belize", "Bolivia", "Brazil", "Chile", "Colombia",
        "Costa Rica", "Cuba", "Curacao", "Dominican Republic", "Ecuador", "El Salvador", "Guatemala",
        "Guyana", "Haiti", "Honduras", "Jamaica", "Mexico", "Nicaragua", "Panama", "Paraguay",
        "Peru", "Suriname", "Trinidad and Tobago", "Uruguay", "Venezuela"
    ],
    "Middle East and North Africa": [
        "Algeria", "Bahrain", "Egypt", "Iran", "Iraq", "Israel", "Jordan", "Kuwait", "Lebanon",
        "Libya", "Mauritania", "Morocco", "Oman", "Qatar", "Saudi Arabia", "Syria", "Tunisia",
        "United Arab Emirates", "Yemen"
    ],
    "North America": ["Canada", "USA"],
    "Russia & CIS": [
        "Armenia", "Azerbaijan", "Belarus", "Kazakhstan", "Kyrgyzstan", "Moldova", "Russia",
        "Tajikistan", "Turkmenistan", "Uzbekistan"
    ],
    "South Asia": [
        "Afghanistan", "Bangladesh", "India", "Maldives", "Nepal", "Pakistan", "Sri Lanka"
    ],
    "Unknown": [
        "Andorra", "Antigua and Barbuda", "Bhutan", "Comoros", "Dominica", "Federated States of Micronesia",
        "Fiji", "Grenada", "Kiribati", "Liechtenstein", "Marshall Islands", "Monaco", "Nauru", "Palau",
        "Palestine", "Puerto Rico", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines",
        "Samoa", "San Marino", "Sao Tom and Principe", "Solomon Islands", "Timor-Leste", "Tonga", "Tuvalu",
        "Unknown", "Vanuatu", "Vatican City", "Western Sahara"
    ]
}

VALID_OPERATORS = [
    "Army", "Navy", "Air Force", "Defense Wide",
    "Ukraine (Assistance)", "Foreign Assistance", "Other"
]

SUPPLIER_LIST = [
    "22nd Century Tech", "A&P Group", "A&R Pacific -Garney Federal", "AAR Supply Chain Inc.", "Aardvark Clear", "AASKI Technology", "AAVCO", "Abacus Tech Corp", "Abdallah Al-Faris", "Abeking Rasmuss",
    "ABG Shipyards", "ABM Shipyard", "Absher Construction Co.", "Abu Dhabi MAR", "Abu Dhabi SB", "ACC Construction Co.", "Accenture", "Accurate Energetic Systems", "ACE Technology", "Aceinfo Solutions",
    "ACHILE Consortium", "Achleitner", "ACMI", "ACT-Corp", "ActioNet", "ADCOM Systems", "ADI Group", "Admiralty Ship", "Advanced Navigation and Positioning Corp.", "Advanced Technology International",
    "AdvElect Co (AEC)", "AECOM", "Aegis Technologies", "Aeraccess", "Aero Def Systems", "Aero Synergie", "Aero Vodochody", "Aerodata AG", "Aerodyca", "Aerojet Rocketdyne", "Aeromaritime Grp", "Aeromot",
    "Aeronautical Development Establishment", "Aeronautics Defense Systems", "Aerospace Corp", "Aerostar", "Aerostar S.A.", "Aerotree", "AeroVironment", "AeroVolga", "Affigent",
    "Africa Automotive Distribution Service", "Agat", "AgEagle", "Agiliti Health", "AICI-Archirodon JV", "AIDC", "AIM Defence", "Air Center Helicopters", "Air Tractor", "Airbus", "Airbus-Rheinmetall",
    "Airborne Tactical Advantage Co.", "Aircell", "Aircraft Readiness Alliance", "AirRobot", "AIS Engineering", "Akkodis", "Albadeey", "Albatross Industria Aeronautica Ltd.", "Alcatel-Lucent", "Alcock Ashdown",
    "Alexandria Ship", "Alion Science", "Allen-Vanguard", "Alliant Techsystems Operations", "Allison Transmission", "Alpha Marine", "Alpine Armoring Inc.", "Altawest", "Altec Industries", "ALTECH Services",
    "Aleut Federal", "Alzchem Trostberg", "AM General", "Amazon", "Amentum Services", "American International Contractors", "American States Utilities Services", "American SysCorp", "American Systems Corp",
    "AMESYS", "AMI Industries", "AMO ZIL", "Amper Group", "AMSL Aero", "AMTEC Corp.", "AMX International", "Amyx Inc", "AMZ-Kutno", "Anadolu Shipyard", "Analytic Services", "Ananda Shipyard", "Andrea Systems",
    "Andritz Hydro Corp.", "Anduril Industries", "Antonov", "ANVL", "AOI", "Apogee Engeineering", "Applied Mechanics", "Applied Technology", "Applied Visual Technology", "APS", "Aquacopters", "Aquila Aerospace",
    "Arab Contractors", "Arcfield Canada", "Archer Aviation", "Archer Western", "Arcturus UAV", "ARES Shipyard", "Aresa Shipyard", "ARGE K-130", "ARGE NNbS Consortium", "Argon ST Inc.", "ARGE DiNa 155", "ARIS",
    "Arma", "Armenian Air Force Institute", "American Electronics Warfare Associates", "American Ordnance", "Armour International", "Armoured Car Sys", "ARMSCOR", "Armtec Defense Products",
    "Arnold Defense and Elec", "ARO SA", "Arotech Corp", "Arquus", "Array Information", "Arrow Edge LLC", "AR-SAT", "Arsenal d' Marinha", "Arsenal JSCO", "ARTEC", "ARTEL, Inc", "ASC Pty Ltd",
    "Ascent Flight Training Consotium", "Ascom Group", "Aselsan", "ASENAV", "Asian ArmoredVeh", "ASIMAR", "ASISGUARD", "Ashot Ashkelon", "ASL Group", "Aslemetals Oy", "ASMAR", "ASRC Federal", "ASRY",
    "Assurance Tech", "Assured Information Security Inc.", "Aster Engineering", "Astilleros Armon Vigo SA", "Astilleros Navales", "ASTIMAR", "Astronics Test Systems", "ASTRUM", "AT&T", "A-techSYN",
    "Atheeb Integraph Saudi Co.", "Atlas", "Atlas Elektronik", "Atlas Group", "ATR", "August Schell Enterprises", "Aurora Flight Sciences", "Austal Limited", "Australian Target Systems", "Autoespar SA",
    "Automotive Ind Ltd", "AUVERLAND", "Aviation Repair Technologies", "Aviation Systems Engineering", "Aviation Training Consulting", "Avibras", "AVIC", "AVNL", "Avtech Corporation", "Avtokraz Holding Co",
    "AWEIL", "AWSR Shipping", "B&F", "Babcock Group", "BAE Systems", "Ball Corporation", "Baltic Workboats", "BAMS", "Bangkok Dock", "Barrett Comm", "Basler", "Bason Shipyard", "Bath Iron Works", "Battelle",
    "Baud Telecom Co", "Baykar", "Bechtel Group", "Becker Avionics", "Beechcraft", "Beherman Demoen", "Beijing JeepCorp", "Bell", "Bell Boeing", "Bell Textron", "Bellanca", "BEML-India", "Bender Shipbldg",
    "Bergen Group", "Beriev", "BGI-ASI JV", "Bharat Dynamics", "Bharat Elec Ltd", "Bharat Heavy Electricals", "Bharat Sanchar", "Bharati Shipyard", "Bigelow Family Holdings", "Bin Jabr Group", "Bird Aerosystems",
    "Birdon", "Bittium", "BL Halbert International", "Black Box Corp", "Black Micro Corp", "Black River Systems", "Blackberry", "Blackned", "BlackSky", "BlindermanPower", "Blue Air Training", "Blue Ivy Partners",
    "Blue River Consortium", "Blue Tech Inc", "Bluebird", "BlueHalo", "Boeing", "Boelwerf Shipyard", "Bollinger Shipyard", "Bombardier", "Booz Allen Hamilton", "Boresight", "Boustead DCNS JV",
    "Boustead Holding", "Bowhead", "Brahmos Ltd", "BrainGu LLC", "Bridgestone Aircraft Tire Inc.", "Britten-Norman", "Brodosplit Shipyard", "Brooke Marine", "Bryan 77 Construction", "BSVT", "BSVT-NT",
    "BT Group", "BUAA", "BwFuhrparkService", "BWI", "By Light", "CACI", "CAE USA", "Cairns Slipways", "Calian", "Calidus", "Cambridge Intl Systems", "Cammell Laird SB", "Canadair", "Cantieri Navali",
    "Carahsoft Inc.", "Cardama", "Carnegie Mellon University", "CASC", "CASIC", "C-Astral Aerospace", "C-AT", "Caterpillar", "CATIC", "CDO Technologies", "CDW Corporation", "CEA Tech Pty Ltd", "Celier Aviation",
    "CENTECH GROUP", "Cerbair", "Cessna", "CFM International", "CGI", "Chaiseri Metal & Rubber", "Changhe", "Chantier Davie Ship", "Charles Stark Draper", "Chas Kurz", "Chemring", "Chengdu",
    "Chowgule and Company", "Chrysler Group", "Chugach Technical Solutions", "Chung Shan Inst", "Cianbro", "CINAR", "CIO", "Cirrus Aircraft", "Cisco Systems", "Clark Construction Group",
    "CM de N (France)", "CNF Technologies", "CNIM", "CNN Navigation", "Coastal Defense Inc.", "Cobham", "Cochin Shipyard", "CODALTEC", "Codan", "Cohort plc", "Cohu Inc", "Colby Co. LLC",
    "Cole Engineering Services", "Collins Aerospace", "COLSA", "Colt's Manufacturing Co.", "Columbia Helicopters Inc.", "COM DEV International", "Comlenia", "Commander Aircraft Corporation",
    "Commtact", "Computacentre", "CompQsoft", "Computer World Services", "COMSOFT", "ComtechTelecomm", "Conco Inc.", "Conlog Group", "Conoship Intl", "Conquest USA", "Consigli Construction",
    "Consortium Management Group", "Conti Federal Services", "Continental Maritime", "Core Tech International", "Core4ce", "Corporacion De La Industria Aeronautica Colombiana", "Corvid Technologies",
    "COTECMAR", "CounterTrade", "CoVant Technologies", "CPMIEC", "Credence Mgmnt Sol", "Creotech", "Crew Training International", "CRIST", "Criterion Solutions", "CRL Technologies", "Crowley Maritime",
    "CRSA", "Crystal", "CSBC Corp., Taiwan", "CSC", "Cubic Corporation", "Cukurova Holding", "Cummins Inc.", "Curt Nyberg", "Curtiss-Wright", "Cybaero AB", "Dae Sun Shipbldg", "Daewoo", "Daher", "Daimler AG",
    "Dakota Creek", "Dalnyaya Radio", "Damen Shipyards", "DAMEX Shipbldg", "Danbury Mission Technologies", "Danish Maritime", "Danish Yacht", "Danyard Aalborg", "Darkhive", "DARPA", "Dassault", "Dassault Dornier",
    "Data Link Solutions", "Data Sys Analysts", "Datamir", "DataPath", "Day & Zimmerman Lone Star", "Dayton T. Brown Inc.", "DCCA", "DCD-DORBYL", "DCI", "DCNS Odebrecht", "DCS Corp.", "De Havilland Canada",
    "Dearsan Shipyard", "Decisive Analytics", "Deep Trekker", "Defense Ind Org", "Defense Industries Organization Of Iran", "Defense Solutions", "Defense Technology Institute", "Defenture", "Deftools",
    "Delaware Nation Industries Emerging Technologies", "Dell Inc", "Deloitte", "Denel", "Derecktor Shipyard", "DESA", "Design West Technologies", "Destini Berhad", "Detyens Shipyard", "DEW Ltd", "DFDS Group",
    "Diamond Aircraft", "DIANCA", "DIDEP", "Diehl", "Digital Angel Corp", "Digital Management", "Diligent Consulting", "Divelink Underwater", "Diversified Tech Svcs", "DJI", "DKW Communications", "DOF ASA",
    "Domo Tactical Communications", "Doosan Group", "Dornier", "Draken", "Draper Labs", "DRB-HICOM", "DRDC Canada", "DRDO", "Drew Marine USA", "DRS Network and Imaging Systems", "DSD Laboratories", "DSG",
    "DSN Corp", "DSTA", "Ducommun Inc.", "DXC Technology", "Dynamic Systems", "Dynamics Resrch", "Dynamit Nobel", "DynCorp Int'l", "Dynetics Technical Solutions", "Eastern Shipbuilding", "ECAN", "ECRN",
    "ECS Federal", "Emcube Inc", "Edgar Brothers", "Edge Autonomy", "EDGE Group", "Edison Chouest", "EFR Ltd", "eGlobalTech", "EID S.A.", "Eire Forge and Steel", "EINSA", "ELAC Sonar GmbH", "Elbit Systems",
    "ELBO", "Elebra", "Electra", "Electric Boat Corp.", "Electro Optic Systems", "Elettronica SpA", "ELINC", "EllisDon", "EM Solutions", "Embraer", "EMESEC", "EMGEPRON", "Emit Aviation", "EMPL Austria", "EMPORDEF",
    "EMS Tech", "EMT", "EMW", "ENAER", "EnerSys Energy Products", "Engility Corporation", "Engine Eng Oman", "ENICS", "Ensign Bickford", "Enstrom Helicopter", "Entrol", "Environics Oy",
    "Environmental Chemical Corp", "Envision Technology", "Envisioneering Inc.", "EONIC", "EOS", "EPC2 Consortium", "EPE", "EPIIC Consortium", "Eprius", "EPS Corporation", "Epsilon Systems", "ESSI/SEI",
    "Esterline", "Eurofighter", "EuroMIDS", "EUROPAAMS", "Eurosam", "Euroshop SA", "EuroSpike", "Exail", "Excellus Solutions", "Exeter Group", "Extra", "FABREQUIPA", "Fabryka Broni", "FAdeA",
    "Fairchild", "Famae", "FAME SAC", "Fasharkan Ship", "Fassmer", "FAW Group", "FCN Technology Sol", "FEDITC", "Federal Contracting", "FedStore Corp", "FemmeCompInc", "Fenix Air Inc.", "FFA", "FFA Emmen",
    "Firestorm Labs", "Five Rivers Analytics", "Fiat Group", "Fiat-Leonardo", "Flatter Inc.", "Fidelity Technologies", "Fincantieri", "Fischer Panda", "Flensburger Fahrzeugbau", "Flensburger SB",
    "Flight Technologies", "Flightcell Intl", "FLightSafety", "FLIR", "Fluor Marine Propulsion", "Flyer", "Flying Legend", "FMA", "FN Herstal", "FNSS", "Fokker", "Force 3", "Ford Motor Co.",
    "Forum Energy Technologies", "FREIRE Shipyard", "Frequentis GmbH", "Fresia SPA", "Frontgrade Technologies", "Frontier Electronic Systems", "FSC Lublin Auto", "FSUE Neptune", "Fujitsu",
    "Furuno Electric", "G & F Technology", "G1 Aviation", "Gabler Maschine", "GAF", "Game Composites", "Garco Construction Inc.", "Garden Reach SB", "Garmin", "Gate Elektronik", "GC Rieber Shipping",
    "GDELS-Mowag", "GECI", "Gemelli", "Genasys", "GenCorp", "General Atomics Aeronautical Systems", "General Dynamics", "General Electric", "General Motors", "Generic Supplier", "Geneset Powerplants",
    "Georgia Tech", "German Naval Yards", "GESPI", "GFE", "Gibbs & Cox Inc.", "GIDS", "Gilbane Federal", "GKN Aerospace", "Gladding-Hearn", "Global GndSpt LLC", "Global Military Products", "Global Services LLC",
    "Global Tech Res", "Global Technical Sys", "Globecomm", "GMV Aerospace and Defense", "Goa Shipyard Ltd", "Golcuk", "Goodrich Corp.", "Goodyear Tire and Rubber Co.", "Grabba", "Granite-Obayashi",
    "Granta Autonomy", "Grevicom SAC", "Griffon Corporation", "Grob", "GRYFIA", "GTRI", "Guimbal", "Guizhou", "Gulf Island Marine Fabricators LLC", "Gulfstream", "Guyco Inc.", "GZAS", "H2O Guam JV", "Hadean", "Hai Minh Corporation", "Haivision Systems Inc.", "HAL", "Hanjin Indust'l SB", "Hanwha", "Harbin", "Harland & Wolff", "Harper Construction", "Harris", "Harwar International Aviation Technology", "Hatehof", "Hawaiian Rock Products Corp.", "HB Utveckling AB", "HAVELSAN", "HDT Expeditionary Systems", "Head/Diaz 2022", "Heavy Ind. Taxila", "Heckler & Koch", "Helibras", "Helicentro Peru SAC", "Hellenic Aerospace Industries", "Hellfire LLC", "Hensel Phelps Construction", "Hensoldt", "HESA", "HexagonComposite", "Hinduja Group", "Hindustan Ship", "Hi-Q Engineering", "Hisdesat SA", "Hitachi", "Hitachi Kokusai", "Hitzler Werft", "HKV", "Hodges Transportation", "Honeywell", "Hong Ha Shipbuilding", "Hong Leong Group", "Hongdu", "Horizon Technologies", "Hornbeck Offshore Operators", "Howe and Howe", "HP", "HPI Solutions", "HTX Labs", "Hughes Comm", "Humbert Aviation", "Huneed Tech", "Huntington Ingalls", "Huta Stalowa Wola", "HV Joint Venture", "Hydra Technologies", "Hydrema", "Hyundai", "Hyundai J Comm", "IAI", "IAP Worldwide Svc", "IAR", "IBM", "ICF", "Icom Inc.", "ICOMM Tele Ltd.", "IdeaForge", "iGOV", "IHI", "II-VI Aerospace and Defense", "Ilyushin", "ImagineOneT&M", "IMBEL", "IMC Group", "IMCO", "immixGroup", "IMMSI SPA", "IMPSA", "Imtech Marine", "INACE", "Indonesian Aerospace", "Indra", "Indrasoft", "INDUS Technology", "InDyne", "InfoReliance Corp", "Infotron", "Inmarsat", "Innocon", "Innnovaero", "Insitu", "Insta ILS", "Institute of International Education", "INTA", "Integ Surv Tech", "Integral Consulting Services", "Integral Systems", "Integrated Convoy", "Integrated Defense Solutions/Greit", "Integrated Dynamic", "Integrated Dynamics", "Integrated Surveillance and Defense", "Integration Innovation", "Intelligent Decisions", "Intelligent Waves", "INTELSAT", "Inter-Coastal Electronics", "InterCaribbean Airways", "Intermarine", "International Business Machines Corp.", "Intl Shipholding Corp", "Intman SA", "Intracom SA", "INVAP", "Invariant Corp.", "INVISIO", "IOMAX", "IPS Inc", "Iridium Satellite", "Iron Bow Tech", "Irving Shipbldg", "Israel Military Industries", "Israel Shipyards", "ISRO Internal", "Istanbul Shipyard", "Isuzu Motor Co", "Italcantieri", "Italtel", "Italthai Marine", "ITG", "ITI Limited", "ITP Aero", "ITT", "Iveco Defence Vehicles", "Iveco-Oto Melara Consortium", "IVEMA", "IWI", "IXBlue", "Izhmash Unmanned Systems", "Jacobs Eng Group", "Jacobs/B&V JV", "James Fisher", "Jankel", "Japan Marine United", "Japan Steel Works", "Javelin JV Team", "JCB", "Jelcz-Komponenty", "Jet Tekno", "JetZero", "JF Taylor", "JHU/APL", "Joby Aviation", "Johns Hopkins University", "Jong Shyn Ship", "JRC Group", "JSC Almaz-Antey", "JSC Kurganmashzavod", "JSC Tactical Missiles Corp", "Junghans Microtec", "Jupiter Wagons Ltd.", "KADDB", "Kader", "KAI", "Kaman", "KAMAZ", "Kamov", "Kangnam Corp", "Karachi Shipyard (KSEW)", "Katmai Management Services", "Katmerciler", "KATO Engineering", "Kawasaki", "Kay and Associates", "Kazakhstan Eng", "Kazan", "KBM Kolumna", "KBP Instrument", "KBR", "Kearfott Corp", "Keppel Corp", "Kerametal", "Kership", "Khan ResLabs", "Kharkiv Morozov", "Khulna Shipyard", "Kiewit-Alberici SIOP MACC", "King ICT", "King Technologies", "KIRINTEC", "KNDS", "Knight Sky", "Knights Armament Co.", "Koam Engineering", "Koc Group", "KomatsuIndustries", "Kongsberg", "KONSTRUKTA", "Kord Technologies", "Korea Shipbuilding & Offshore Engineering", "Korte Construction", "Agency for Defense Development", "Korean Air Aerospace Division", "KRAS - India", "Krasmashzavod", "Kratos Defense", "Kronshtadt Group", "Krauss-Maffei Wegmann", "Kryukov Car Bldg", "KT Consulting", "KVH Industries", "Kyndryl Finland", "L3 Technologies", "Lancair", "Landmarc", "Lane Construction Corp.", "Larsen & Toubro", "Leidos", "Leonardo", "LET", "Level 3 Comm", "Life Cycle Engineering", "LG Group", "LIG Nex1 Co", "LinQuest Corp", "LinTech Pragmatics JV", "Lite Comms LLC", "Lockheed Martin", "Loc Performance Products", "LOM PRAHA", "Long Wave Inc", "Longbow LLC", "Loral", "Lumen", "Lumenier", "Lung Teh Shipbldg", "Lurssen Group", "Lutch", "Lutsk", "M Ship Co", "M1 Support Services", "M2 Technologies", "M7 Aerospace", "Mach Industry Grp", "Mack Defense", "Mackay Comm", "MAESTRAL", "Maestranza AMSU", "MAG Aerospace", "Magellan Aerospace Corporation", "Mahindra", "MA Mortenson", "MAN", "Manhattan Construction", "ManTech", "Mapiex Aviation", "Marine Alutech Oy", "Marine Hydraulics", "Marine United", "MarineTec", "Marinette Marine Corp.", "MARS Shipyards", "Marsh Aviation", "Marshall Aerospace", "MARSS", "Marsun Company", "Martifer Group", "Marvin Land System", "Mastodon Design", "Mathtech", "Maule Air", "MAV", "Maxar Technologies", "Mazagon Dock", "MBB", "MBDA", "McCrone Associates", "McDermott Marine", "McLean Contracting", "MD Helicopters", "MDA Space", "MDT Armour", "MechDB S Africa", "Mectron", "MEDAV GmbH", "Mercedes-Benz", "Mercer Engineering Research Centre", "Mercury Systems Inc.", "Merlin Labs Inc.", "Merwede", "Mesko", "MESIT holding", "Messer Construction", "Metal Shark", "MetalCraft Marine", "Metalnor SA", "Meyer Werft", "Michelin", "Micro Aviation", "Microdis Electronics", "Micropol Fiberoptic AB", "Microsoft", "MicroTech", "Middle East Def", "Mikal Group", "Mikoyan", "Mil", "MilDef", "Milenium Veladi Corp.", "Millenium Space", "MilSOFT Software", "MineWolf Systems", "MISC Berhad", "Mission1st", "Mistral Inc.", "Mitie", "Mitsubishi", "Mitsui SB", "MKEK", "MMIST", "MNDI Pacific JV", "MO Porte-Avions", "Modern Technology Solutions", "Moller-Maersk", "Moog Inc.", "MorseCorp Inc.", "Morye Shipyard", "Motorola Solutions", "MSI", "Mudry", "Mugin", "MVL USA", "MW Builders", "Mythics", "Nakilat", "Nakupuna Consulting", "NAMC", "Nammo", "Nan Inc.", "Nanchang", "National Academy of Sciences of Belarus", "National Steel and Shipbuilding", "Natl Radio Telecom", "Nautica Nova", "Naval Gijon Ship", "Naval Group", "Naval Shipyard Gdynia", "Navantia", "Naviris", "Navistar International", "Navmar", "NCI Info Sys", "NCSIST", "ND Defense", "NDMA", "NEC", "Neiva", "Neorion Group", "NES Associates", "NetCentrics Corp", "Netline Comm", "New Directions Technologies", "NewSpace India", "NEWTEC", "Nexter", "NGV Tech", "NH Industries", "NICCO Comm", "Nigerian Dockyard", "NII STT", "Niigata Shipbuilding", "NIMR Auto", "Nissan", "nLIGHT Nutronics", "Noble Supply and Logistics", "Noblis MSD", "Nokia", "Nordic Terrain Solutions", "Norinco", "Norma Precision AB", "Nortel", "North Sea Boats", "Northrop Grumman", "Northstar Aviation", "Nostromo", "Novadem", "NP Aerospace", "NPO Elektro'ka", "NPO Lavochkin", "NRL", "NSSL", "NSWC", "NT Service", "NTConcepts", "nTSI", "NTT Group", "NUBURU", "Nurol Co.", "NVL Group", "Oakwell Engineer", "OBRUM", "OCEA Group", "Ocean Shipholdings", "Ocean Tech Sys", "Oceaneering", "OCR Global", "Odebrecht Group", "Odyssey Systems Consulting Group", "OGMA", "OHB System AG", "OIP Land Systems", "Old North Utility Services", "Olin Winchester", "Omnisec AG", "Omnisys", "Ondas", "Optics1 Inc.", "Optima Government Solutions", "Orbit Technologies", "Orizzonte Sistemi Navali", "Orskov Group", "Oshkosh", "OSI", "Otobus Karoseri", "Otokar", "OTT Technologies", "Out of Business", "Overaasen AS", "Ovzon", "PAC", "Paccar", "Pacific Aerospace", "Pacific Rim Constructors", "Pacifics Propeller International", "PAE Aviation and Technical Services", "Pakistan Aeronautical Complex", "Palantir Technologies", "Palantir USG", "Palfinger", "PAMA-SP", "PanAmSat", "Panavia", "Panha", "Paramount Group", "Parker-Hannifin", "Parrot", "Parsons Government Services", "Patria", "Patriot Contract Svcs", "PCCI", "PCM", "Pearson Engineering", "Peerless Technologies", "Pelatron", "Pelegrin", "Penman Company", "Peraton Technology Services", "Persistent Systems", "Peterson Bldrs", "PGSUS", "PGZ", "PGZ-PILICA Consortium", "PGZ-NAREW Consortium", "Phacil Inc", "Phoenix Air Group", "Philadelphia Yard", "Philippine Telephone", "Piaggio", "Pilatus", "Pindad", "Piper", "Pipistrel", "Piriou Naval Svcs", "PJ Aviation", "PKL Services", "Plath", "PN Dockyard", "Polaris Industries", "Polish Defence Holding", "Polska Grupa", "Polskie Zaklady Lotnicze", "Poly Technologies", "Polyot", "Polysentry", "Pragmatics", "Presidio", "Priboy", "PRIMA Research", "Proforce Defence", "Programs Management Analytics and Technologies", "Propmech Corp", "Prox Dynamics", "PS Engineering", "PSI", "PSM", "PT Batam", "Pt Bhinneka Dwi Persada", "PT Citra Barahi Shipyard", "PT Daya Radar Utama", "PT Dirgantara", "PT Dumas Shipyard", "PT Kodja Bahari", "PT PAL Indonesia", "PT Palindo", "PT Republik Defensindo", "PZL-Mielec", "PZL-Okęcie", "PZL-Swidnik", "Q-Techn LLC", "Qbase, LLC.", "QED Systems Inc", "QinetiQ", "Qioptiq", "Qods Aviation Industries", "Quad City Aircraft", "QualX Corp.", "Quantum Research", "Quantum Systems", "QuantX Labs", "Qwest", "R&W Contractors", "Radiance Tech", "Radmor SA", "Rafael", "RAM Systems", "RAMET", "Range Generation Next", "Rannoch Corp", "Rauma Marine", "Ravenswood Solutions Inc.", "RAVN Group", "Raytheon Technologies", "RC Construction", "Rebellion Defense", "ReconCraft LLC", "Record Steel & Construction", "Red Peak Technical Services", "Red River Computer", "Redflex Group", "Redwire", "Regional One", "Reims-Cessna", "Reiser", "Reliance Defence", "Reliance Test and Technology", "Remdiesel", "Remontowa Group", "Remoy Shipping", "Renk America", "Repkon USA-Defense", "Reshetnev Company", "Ressenig", "Reunert", "Revolution Aviation", "Rh-Alan", "RHEA Group", "Rheinmetall", "Rheinmetall BAE Systems Land", "Rheinmetall Denel", "Rheinmetall MAN", "Ribcraft USA", "Ricardo PLC", "Riga Shipyard", "RIO Design Bureau", "Rio Santiago Shipyard", "Rise8 Inc.", "RiverHawk Group", "Robertson Fuel Systems", "Robin Radar Systems", "Robinson", "Roboteam", "Rocket Lab National Security LLC", "Rockwell Collins", "Rodman Group", "Rohde & Schwarz", "Roke", "Roketsan", "Rolls-Royce plc", "Roman Brasov", "ROMARM", "Rosomak", "Rostec", "Rothe Development", "Rovsing A/S", "RQ Construction", "RS-UAS", "RTX", "RUAG", "RV Connex", "RWG Repair & Overhauls USA", "Saab", "Sabiex Group", "Sabre Systems", "Sabreliner Corporation", "SAFAT", "Safe Boats Intl", "Safran", "Sagemcom", "SAIC", "Sako", "SAL", "Salient CRGT Inc", "Sallyport Global Holdings", "SAN", "San Yang", "Sandia Nat Labs", "Sanmina-SCI", "Sanska", "Santana Motors", "Santierul Naval", "SANUKI Shipbldg", "SAPURA", "Sapura Thales", "Sarco Defense", "Sasebo Heavy Ind", "Satuma", "Savox Communications", "SBIC", "Scandinavian Avionics", "Scania", "Scheepvaart KB", "Schiebel", "Schweizer", "Schutt Industries", "Science and Engineering Services", "Science Applications International", "Scientia Global", "Scientific Research Corp.", "Scorpene JV", "SCOTTY Group", "SCR", "SEA", "Seabird Aviation", "Sealift Inc", "Seaspan Marine", "Seaward Marine Services", "Second-Hand", "Sectra Comm Sys", "SecuriGence", "Sedef Shipbuilding", "Seed Innovations", "Seemann Composites LLC", "Sefine Shipyard", "Segue Technologies", "Selah Shipbuilding", "SELEX Elsag", "Selex ES", "SEMAN Peru", "SEPECAT", "SEPI", "Sepura", "Serbian State", "Serco Group plc", "SES", "SETEL/REMSCO", "SGJV", "Shaanxi", "Shaanxi Auto Grp", "Shenyang", "Shijiazhuang", "Shin Maywa Industries", "Shin Yang", "Shoft Shipyard", "Short Brothers", "SI Systems Technologies", "SICC", "Sielman S.A.", "Siemens", "Sierra Nevada", "SIG Sauer", "Sigen Consortium", "Sikorsky", "Silent Sentinel", "Silver Ships Inc.", "SIMA Peru", "Singapore Tech.", "SingTel Group", "SISDEF", "Sistemprom", "Sisu Auto", "SITAB Consortium", "SK Holdings", "Skanska", "SkyAlyne", "Skydio", "Slingsby", "SmartShooter", "Smartronix Inc", "SMS Data Products", "SNC-Lavalin", "SNVI", "Sobeca", "Soby Vaerft", "Socarenam", "Socata", "Sodexo Management Inc.", "SOFIS-TRG", "SOFRAME", "Sojitz Corporation", "Soko", "Solar Industries", "Solers", "Solstad Offshore", "SONAK", "Sonalysts Inc.", "Songthu Corporation", "Southern African Ship", "Southern Maryland Electric Cooperative", "Southern Resc'h", "Southwest Resc'h", "Soviet Tank Plant", "Sozvezdie JSC", "SPA", "Spaceflux", "SpaceX", "Spanish Missile Systems", "Sparton De Leon Springs LLC", "Special Technology Ctr", "Spectra", "Spectrum Comm", "SpearUAV", "SpeedCast", "Sprint", "SR Telecom", "SRC", "SRCTec", "ST Aerospace", "StandardAero Inc.", "Stark Aerospace", "Stauder Technologies", "Sterling Computers", "Steyr", "STG", "Stinger ProjectGP", "STM Group", "Streit Group", "STS International", "STX Corporation", "Subaru", "Submarine Manufacturing and Products", "Sukhoi", "Sumaria Systems", "Sumidagawa Ship", "Sumitomo", "Summit Aviation", "Sunair", "Supacat", "Superior Govt Sol", "Superior Marine Ways", "Surrey Satellite Technology", "Survey Copter", "Suzuki Motor Corp", "SVI Engineering", "Swan Hunter", "Swecon", "Swede Ship", "SwedishSpace Cp", "Swiftships SB LLC", "Symetrics", "Synectic Group", "Sypaq Systems", "Sypris Solutions", "Sys for Def/GVS", "System Studies & Simulation", "Systematic", "Systems Planning and Analysis", "T. Mariotti", "Tactical Air Support Inc.", "Tactical Engineer", "TADANO", "TAE Aerospace", "TAI", "Talbert Manufacturing Inc.", "Target Technologia", "Taskizak Shipyard", "TAT Technologies", "Tata Advanced Systems", "Tata Group", "TATRA", "Taurus Systems", "Taylor Defense Products", "TCG", "TCIL", "TDW GmbH", "TDX International", "Technica Corp", "Technical Comms", "Technology Unlim", "Tecnam", "TECNOBIT", "Tekever", "Telecomm Systems", "Teledyne", "Teledyne FLIR", "Telephonics Corp.", "Telespazio", "Teletronics Technology", "Telia Finland", "Tellumat", "Telos Corp", "Telstra", "Terberg Group", "Terma A/S", "Tesat Spacecom", "TESCO INDOMARITIM", "TESLA", "TESS Defence", "Tesseract Ventures", "TETRAEDR", "Texas A&M", "Textron", "Thales", "Thales Alenia Sp", "ThalesRaytheon", "The MIL Corp.", "The Whiting-Turner Contracting Co.", "TWPG", "THEON International", "ThirdEye", "Thoma-Sea Ship", "Thrane & Thrane", "Threod Systems", "Thuraya", "ThyssenKrupp AG", "Timken Gears & Services", "Titan Aircraft", "TKC Global Solutions", "TNO", "Tobyhanna Army", "Tomahawk Robotics", "Top Aces", "Toshiba", "Toyota Motor Corp", "Trans-Ce Cargo SA", "Transall", "Transas Group", "Transbit", "Transfield Services", "TRAX International", "TrellisWare Tech", "Trideum Corp", "Triman Industries", "Triton Group Hold", "TRU Simulation Plus Training", "TRX System", "TSS Solutions", "TTC TELEKOM", "TUBITAK", "Tupolev", "Turkish AFF", "Turner Construction", "Twin Commander Aircraft", "TYBRIN", "Tyco Intl", "Tyovene", "Tyto Athene", "Tyvak International", "UAV Communications", "UAV Solutions", "Uavision Aeronautics", "UCOCAR", "Uconsystem", "UK Docks Marine Services", "Ukraine Weapons", "UkraineTank Plant", "Ukroboronprom", "Ukrspecsystems", "Ulijanovsk", "UltiSat", "Ultra Dimensions Pvt. Ltd.", "Ultra Electronics", "Ultra I&C", "Ultra Maritime", "UMM", "Umoe Group", "Unicom", "Unicom Government", "Unknown", "Unified Industries", "UNIMO Technology", "Unimor Radiocom", "Unisys", "Unit Co.", "United Crane and Excavation Inc.", "United Electronics", "United Launch Alliance", "Univ of Texas", "Univ of Toronto", "Universal Shipbldg", "Unman'dDynamics", "Ural Works Civil Aviation", "Uralvagonzavod", "URC Systems", "UROVESA", "US Marine Inc", "US Ordnance", "USCG YARD", "UTVA", "UVision Global Aero", "Valero Marketing and Supply", "Valiant Global Defense", "Valkyrie Aero", "Van's Aircraft", "Multiple", "Vector Scientific", "Vector Solutions", "Vectrus Systems Corp.", "Vega Company", "Vencore", "Veritas Capital", "Verizon", "Vertex Aerospace", "Vertex Standard", "Vestel", "ViaSat Inc", "Victory Solutions Inc.", "VideoRay LLC", "Viettel Group", "Vigor Industrial", "Viking Air", "Viking Arms", "Vimpel", "Vladimir Radio", "Volkswagen Group", "Volvo Group", "Von Wolf", "VOP 025", "VOP 026 Sternberk", "VPK", "VSE Corp.", "Vulcanair", "V2X", "Walsh Federal LLC", "Wartsila", "Watterson Construction Co.", "WB Electronics", "WBA Blindajes Alemanes", "West Sea Shipyard", "Weststar Group", "WG Yates and Sons", "Wildflower Intl", "Windmill Intl", "World Wide Tech", "WULCO Inc.", "WZE", "WZM", "X-Bow", "Xian", "Xian ASN Technical Group", "XTAR", "Yakovlev", "Yamaha", "Yaroslavl Radio", "Yeonhab Precision", "Yokohama Yacht", "Yoland Corp.", "Yonca-Onuk", "Yugoimport-SDPR", "Zala", "Zamil Offshore", "Zen Technologies", "Zenair LTD", "Zenit Shipyard", "Zenith", "Zlin", "Zwijnenburg", "ZyXEL Comm", "Hydroid Inc", "West Coast JV,", "University of Dayton Research Institute", "Saguaro Business Solutions LLC", "Learjet", "General Dynamics Electric Boat", "Ball Aerospace & Technologies", "TCOM", "Raytheon Missiles and Defense", "Lockheed Martin Missile and Fire Control", "EFW", "Amherst Systems", "Lockheed Martin Sippican", "Hamilton Sundstrand", "Northrop Grumman Aerospace", "R.A. Burch Construction", "Lockheed Martin – Rotary and Mission Systems", "Trace Systems", "Northrop Grumman Space Systems Sector", "L-3 Communications Integrated Systems", "Flint Electric Membership", "Gray Analytics", "Lockheed Martin Aeronautics", "Lockheed Martin Space", "LTM Inc", "Alberici-Mortenson", "Atlantic Signal", "Haight Bey & Associates", "Container Research Corp", "Essex Electro Engineers", "TechFlow Mission Support", "Chugach Range and Facilities Services", "Raytheon Space and Airborne Systems", "Innovative Scientific Solutions", "Delavan", "Covalus", "Chromalloy Component Services", "Armorworks Enterprises", "Metro Machine", "Alloy Surfaces", "Valley Tech Systems", "Keysight Technologies", "Azure Summit Technology", "Isometrics", "Stratascorp", "Synergy Electric Company", "Custom Manufacturing & Engineering", "East West Industries", "MPR Associates", "ARCTOS Technology Solutions", "Enlighten IT Consulting", "Barrett Firearms", "Ametek Programmable Power", "Applied Physical Sciences", "SupplyCore", "Federal Resources", "General Atomics", "Penguin Computing", "Mancon", "Integrated Marine Services", "Compass Systems", "DRS Sustainment Systems", "IronMountain Solutions", "Ball Aerospace & Technologies", "Yulista Services", "SyQwest", "Advanced Technology Systems", "Cleveland Construction", "Canadian Commercial Corp", "Systima Technologies", "Ocean Ships", "Metro Machine Corp", "ImSAR LLC", "Systems Application & Technologies", "Twin Disc", "Konecranes Nuclear Equipment and Services", "Progeny Systems", "WEBCO", "REEL COH", "Waterman Transport", "Western Metal Supply", "Security Signals", "Wolverine Tube", "BC Customs LLC", "TLD America", "Crane Technologies Group", "IDSC Holdings", "AAR Manufacturing", "B & D Electric", "Vector CSP LLC", "Accurate Machine & Tool Corp", "Mississippi State University", "Stephenson Stellar Corp", "Earthly Dynamics", "Woolpert Inc", "Halter Marine", "Marion Manufacturing", "FN America LLC", "CDM Constructors", "Florida State University - Center for Advanced Power Systems", "International Marine & Industrial Applicators", "Zodiac-Poettker HBZ JV II LLC", "DigiFlight", "Globe Composite Solutions", "Meggitt Polymers and Composites", "Martin-Baker Aircraft", "United Kingdom Ministry of Defence", "Ultimate Training Munitions", "PAS Technologies", "DCM Clean Air Products", "Management Services", "Technology Service Corp", "General Electric Aviation", "ACME/RHB", "Howell Industries", "Airdyne Aerospace", "Dominion Energy", "Bionetics", "Choctaw Defense Manufacturing", "Centauri", "DRS Naval Power Systems", "Sentry View Systems", "ERAPSCO", "AAR Government Services", "Management Services", "L3 Doss Aviation", "AgustaWestland Philadelphia", "Marvin Engineering", "Collins Elbit Vision Systems", "FGS", "Navistar Defense LLC", "Voith Hydro", "Delfasco"
]

PROGRAM_TYPES = [
    "Training", 
    "Procurement", 
    "MRO/Support", 
    "RDT&E",
    "Upgrade", 
    "Other Service" 
]

DOMESTIC_CONTENT_OPTIONS = [
    "Indigenous", 
    "Imported", 
    "Local Assembly", 
    "License Production"
]